import { GoogleGenerativeAI } from '@google/generative-ai';
import { buildDebatePrompt } from '../config/promptTemplates.js';
import { getPersonality } from '../config/personalityConfig.js';

/**
 * AI Service Layer
 * 
 * This file acts as the boundary between our application and the Google Gemini API.
 * 
 * Why do we have this?
 * 1. Security: API keys stay on the server.
 * 2. Abstraction: If we ever switch to OpenAI, we only change this file, not the whole app.
 * 3. Error Handling: Centralized place to handle rate limits and timeouts.
 */

// Initialize the Gemini client.
// We do this lazily or handle missing keys so the app doesn't crash on startup if the key is missing.
const getAIClient = () => {
  const apiKey = process.env.AI_API_KEY;
  if (!apiKey || apiKey === 'your_gemini_api_key_here') {
    throw new Error('AI_API_KEY is not configured in .env');
  }
  return new GoogleGenerativeAI(apiKey);
};

export const aiService = {

  /**
   * Generates a conversational response from the AI.
   * @param {Array} history - The chat history
   * @param {String} personaId - The ID of the personality (e.g., 'einstein')
   * @param {String} currentTopic - The topic of the debate
   * @param {String} userMessage - The latest user message
   */
  generateDebateResponse: async (history, personaId, currentTopic, userMessage) => {
    try {
      const genAI = getAIClient();
      // We will use gemini-1.5-flash as it is extremely fast and cost-effective for chat
      const model = genAI.getGenerativeModel({ 
        model: "gemini-1.5-flash",
        // Temperature controls creativity. 0.7 gives varied, natural debate responses
        generationConfig: { temperature: 0.7 } 
      });
      
      const persona = getPersonality(personaId);
      
      // 1. Build the exact prompt (System rules + Memory + User Input)
      const fullPrompt = buildDebatePrompt(persona, history, currentTopic, userMessage);
      
      // 2. Call the AI securely from the backend
      const result = await model.generateContent(fullPrompt);
      const response = await result.response;
      
      // 3. Extract the text generated by the AI
      const text = response.text();
      
      return text;
    } catch (error) {
      console.error("AI Service Error (generateDebateResponse):", error);
      throw new Error("The AI is currently resting. Please try again later.");
    }
  },

  /**
   * Evaluates a completed debate and forces the AI to output strictly structured JSON.
   */
  evaluateDebate: async (messages) => {
    try {
      const genAI = getAIClient();
      const model = genAI.getGenerativeModel({ 
        model: "gemini-1.5-flash",
        // Temperature 0.0 makes the AI highly deterministic and logical, perfect for grading
        generationConfig: { 
          temperature: 0.0,
          responseMimeType: "application/json" 
        }
      });
      
      let historyText = messages.map(m => `${m.sender}: ${m.text}`).join('\n');
      
      const prompt = `You are an expert debate judge and logician.
Analyze the following debate history between a User and an AI.

DEBATE HISTORY:
${historyText}

INSTRUCTIONS:
Evaluate the User's performance. You must return your evaluation strictly as a valid JSON object matching this exact structure, with no markdown formatting around it:
{
  "logicScore": <number 0-10>,
  "evidenceScore": <number 0-10>,
  "persuasionScore": <number 0-10>,
  "summary": "<A 2-sentence summary of the user's main arguments>",
  "fallacies": [
    { "name": "<Name of fallacy>", "explanation": "<Why the user committed this fallacy>" }
  ],
  "feedback": "<1 paragraph of constructive feedback for the user>"
}`;

      const result = await model.generateContent(prompt);
      const text = await result.response.text();
      
      // Since we enforced application/json, the text is guaranteed to be a JSON string.
      return JSON.parse(text);
    } catch (error) {
      console.error("AI Service Error (evaluateDebate):", error);
      throw new Error("Failed to evaluate debate.");
    }
  },
  
  /**
   * Generates a list of debate topics based on a category.
   */
  generateTopics: async (category) => {
    try {
      const genAI = getAIClient();
      const model = genAI.getGenerativeModel({ 
        model: "gemini-1.5-flash",
        generationConfig: { temperature: 0.9, responseMimeType: "application/json" }
      });

      const prompt = `Generate 5 highly controversial and interesting debate topics in the category of "${category}".
Return strictly as a JSON array of strings. Example: ["Topic 1", "Topic 2"]`;

      const result = await model.generateContent(prompt);
      const text = await result.response.text();
      return JSON.parse(text);
    } catch (error) {
      console.error("AI Service Error (generateTopics):", error);
      return ["Is AI dangerous?", "Should healthcare be free?", "Does social media do more harm than good?"];
    }
  }
};
